"""initial schema

Revision ID: eb1765fe2bf5
Revises:
Create Date: 2026-10-02 11:45:33.627316

Creates the 21 CASE tables. The full-text search objects (case_search,
case_search_fts and their triggers) are installed separately by
``app.search.install_search_schema``: they are derived, can always be
rebuilt from the base tables, and their DDL lives with the module that
maintains it.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Referenced below as app.models.types.UnsignedTinyInt; imported
# explicitly so the migration does not depend on env.py having loaded it.
import app.models.types  # noqa: F401


revision: str = 'eb1765fe2bf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('record_pk', sa.Text(), nullable=False),
    sa.Column('action', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)

    op.create_table('dict_herb',
    sa.Column('herb_id', sa.Text(), nullable=False),
    sa.Column('herb_name', sa.Text(), nullable=False),
    sa.Column('pinyin', sa.Text(), nullable=False),
    sa.Column('parent_herb_id', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processing', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('nature', sa.Text(), nullable=False),
    sa.Column('flavor', sa.Text(), nullable=False),
    sa.Column('meridians', sa.Text(), nullable=False),
    sa.Column('functions', sa.Text(), nullable=False),
    sa.Column('standard_code', sa.Text(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['parent_herb_id'], ['dict_herb.herb_id'], name=op.f('fk_dict_herb_parent_herb_id_dict_herb')),
    sa.PrimaryKeyConstraint('herb_id', name=op.f('pk_dict_herb')),
    sa.UniqueConstraint('herb_name', name=op.f('uq_dict_herb_herb_name'))
    )
    op.create_table('dict_syndrome',
    sa.Column('syndrome_id', sa.Text(), nullable=False),
    sa.Column('syndrome_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('standard_code', sa.Text(), nullable=False),
    sa.Column('key_symptoms', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('common_formula', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('syndrome_id', name=op.f('pk_dict_syndrome')),
    sa.UniqueConstraint('syndrome_name', name=op.f('uq_dict_syndrome_syndrome_name'))
    )
    op.create_table('dict_term',
    sa.Column('term_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_type', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('standard_code', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['dict_term.term_id'], name=op.f('fk_dict_term_parent_id_dict_term')),
    sa.PrimaryKeyConstraint('term_id', name=op.f('pk_dict_term'))
    )
    with op.batch_alter_table('dict_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dict_term_term_type'), ['term_type'], unique=False)

    op.create_table('info_patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('patient_name', sa.Text(), nullable=False),
    sa.Column('name_masked', sa.Boolean(), nullable=False),
    sa.Column('id_no', sa.Text(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('nationality', sa.Text(), nullable=False),
    sa.Column('ethnicity', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('birthplace', sa.Text(), nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('tel', sa.Text(), nullable=False),
    sa.Column('addr_region', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_info_patient')),
    sa.UniqueConstraint('patient_id', name=op.f('uq_info_patient_patient_id'))
    )
    op.create_table('mentor',
    sa.Column('mentor_id', sa.Text(), nullable=False),
    sa.Column('mentor_name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('affiliation', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('expertise', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('mentor_id', name=op.f('pk_mentor'))
    )
    op.create_table('source_document',
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('doc_type', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=False),
    sa.Column('hospital', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_strategy', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('file_name_origin', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id', name=op.f('pk_source_document'))
    )
    op.create_table('case_narrative',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('present_illness', sa.Text(), nullable=False),
    sa.Column('past_history', sa.Text(), nullable=False),
    sa.Column('personal_history', sa.Text(), nullable=False),
    sa.Column('allergy_history', sa.Text(), nullable=False),
    sa.Column('body_of_tongue', sa.Text(), nullable=False),
    sa.Column('fur_of_tongue', sa.Text(), nullable=False),
    sa.Column('pulse', sa.Text(), nullable=False),
    sa.Column('other_cond', sa.Text(), nullable=False),
    sa.Column('physical_exam', sa.Text(), nullable=False),
    sa.Column('auxiliary_exam', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['info_patient.patient_id'], name=op.f('fk_case_narrative_patient_id_info_patient')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_case_narrative'))
    )
    op.create_table('diagnosis',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('tcm_disease', sa.Text(), nullable=False),
    sa.Column('syndrome', sa.Text(), nullable=False),
    sa.Column('syndrome_id', sa.Text(), nullable=True),
    sa.Column('wm_diagnosis', sa.Text(), nullable=False),
    sa.Column('patterns_analysis', sa.Text(), nullable=False),
    sa.Column('differential_diagnosis', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['info_patient.patient_id'], name=op.f('fk_diagnosis_patient_id_info_patient')),
    sa.ForeignKeyConstraint(['syndrome_id'], ['dict_syndrome.syndrome_id'], name=op.f('fk_diagnosis_syndrome_id_dict_syndrome')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_diagnosis'))
    )
    op.create_table('dict_formula',
    sa.Column('formula_id', sa.Text(), nullable=False),
    sa.Column('formula_name', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('functions', sa.Text(), nullable=False),
    sa.Column('indications', sa.Text(), nullable=False),
    sa.Column('syndrome_id', sa.Text(), nullable=True),
    sa.Column('composition_text', sa.Text(), nullable=False),
    sa.Column('usage_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['syndrome_id'], ['dict_syndrome.syndrome_id'], name=op.f('fk_dict_formula_syndrome_id_dict_syndrome')),
    sa.PrimaryKeyConstraint('formula_id', name=op.f('pk_dict_formula')),
    sa.UniqueConstraint('formula_name', name=op.f('uq_dict_formula_formula_name'))
    )
    op.create_table('dict_herb_alias',
    sa.Column('alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('herb_id', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('alias_type', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('ambiguity_note', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['dict_herb.herb_id'], name=op.f('fk_dict_herb_alias_herb_id_dict_herb')),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_dict_herb_alias'))
    )
    with op.batch_alter_table('dict_herb_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dict_herb_alias_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_dict_herb_alias_herb_id'), ['herb_id'], unique=False)

    op.create_table('info_record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=False),
    sa.Column('visit_no', sa.Integer(), nullable=False),
    sa.Column('visit_type', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('clinic_date', sa.Date(), nullable=False),
    sa.Column('age', sa.REAL(), nullable=False),
    sa.Column('doctor_name', sa.Text(), nullable=False),
    sa.Column('mentor_id', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('addr', sa.Text(), nullable=False),
    sa.Column('solar_terms', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('source_document_id', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.mentor_id'], name=op.f('fk_info_record_mentor_id_mentor')),
    sa.ForeignKeyConstraint(['patient_id'], ['info_patient.patient_id'], name=op.f('fk_info_record_patient_id_info_patient')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.doc_id'], name=op.f('fk_info_record_source_document_id_source_document')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_info_record'))
    )
    with op.batch_alter_table('info_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_info_record_father_id'), ['father_id'], unique=False)

    op.create_table('mentor_comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('mentor_id', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('commented_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.mentor_id'], name=op.f('fk_mentor_comment_mentor_id_mentor')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('pk_mentor_comment'))
    )
    op.create_table('attachment',
    sa.Column('attach_id', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('thumb_path', sa.Text(), nullable=False),
    sa.Column('file_type', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['source_document.doc_id'], name=op.f('fk_attachment_doc_id_source_document')),
    sa.ForeignKeyConstraint(['record_id'], ['info_record.record_id'], name=op.f('fk_attachment_record_id_info_record')),
    sa.PrimaryKeyConstraint('attach_id', name=op.f('pk_attachment'))
    )
    op.create_table('learning_note',
    sa.Column('note_id', sa.Text(), nullable=False),
    sa.Column('note_type', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('status', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('is_ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.mentor_id'], name=op.f('fk_learning_note_mentor_id_mentor')),
    sa.ForeignKeyConstraint(['record_id'], ['info_record.record_id'], name=op.f('fk_learning_note_record_id_info_record')),
    sa.PrimaryKeyConstraint('note_id', name=op.f('pk_learning_note'))
    )
    op.create_table('prescription_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('prescription_no', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('herb_id', sa.Text(), nullable=True),
    sa.Column('herb_name', sa.Text(), nullable=False),
    sa.Column('herb_name_norm', sa.Text(), nullable=False),
    sa.Column('dose', sa.REAL(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('total_quantity', sa.REAL(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('processing', sa.Text(), nullable=False),
    sa.Column('decoction_note', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['dict_herb.herb_id'], name=op.f('fk_prescription_item_herb_id_dict_herb')),
    sa.ForeignKeyConstraint(['patient_id'], ['info_patient.patient_id'], name=op.f('fk_prescription_item_patient_id_info_patient')),
    sa.ForeignKeyConstraint(['record_id'], ['info_record.record_id'], name=op.f('fk_prescription_item_record_id_info_record')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_prescription_item'))
    )
    with op.batch_alter_table('prescription_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_item_record_id'), ['record_id'], unique=False)

    op.create_table('treatment',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('treatment_principle', sa.Text(), nullable=False),
    sa.Column('formula_name', sa.Text(), nullable=False),
    sa.Column('formula_id', sa.Text(), nullable=True),
    sa.Column('dose_count', sa.Integer(), nullable=True),
    sa.Column('decoction', sa.Text(), nullable=False),
    sa.Column('usage', sa.Text(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('other_treatment', sa.Text(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['dict_formula.formula_id'], name=op.f('fk_treatment_formula_id_dict_formula')),
    sa.ForeignKeyConstraint(['patient_id'], ['info_patient.patient_id'], name=op.f('fk_treatment_patient_id_info_patient')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_treatment'))
    )
    op.create_table('note_record_link',
    sa.Column('link_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('relation', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['learning_note.note_id'], name=op.f('fk_note_record_link_note_id_learning_note')),
    sa.ForeignKeyConstraint(['record_id'], ['info_record.record_id'], name=op.f('fk_note_record_link_record_id_info_record')),
    sa.PrimaryKeyConstraint('link_id', name=op.f('pk_note_record_link'))
    )
    op.create_table('ocr_job',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('attach_id', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('status', app.models.types.UnsignedTinyInt(), nullable=False),
    sa.Column('vision_engine', sa.Text(), nullable=False),
    sa.Column('vision_text', sa.Text(), nullable=False),
    sa.Column('vision_json', sa.JSON(), nullable=True),
    sa.Column('vision_ms', sa.Integer(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=True),
    sa.Column('degraded_mode', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_yuan', sa.REAL(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['attach_id'], ['attachment.attach_id'], name=op.f('fk_ocr_job_attach_id_attachment')),
    sa.ForeignKeyConstraint(['record_id'], ['info_record.record_id'], name=op.f('fk_ocr_job_record_id_info_record')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_ocr_job'))
    )
    with op.batch_alter_table('ocr_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_job_attach_id'), ['attach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_job_status'), ['status'], unique=False)

    op.create_table('ocr_field_confidence',
    sa.Column('conf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('source', app.models.types.UnsignedTinyInt(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ocr_job.job_id'], name=op.f('fk_ocr_field_confidence_job_id_ocr_job')),
    sa.PrimaryKeyConstraint('conf_id', name=op.f('pk_ocr_field_confidence'))
    )
    with op.batch_alter_table('ocr_field_confidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_field_confidence_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_field_confidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_field_confidence_job_id'))

    op.drop_table('ocr_field_confidence')
    with op.batch_alter_table('ocr_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_job_status'))
        batch_op.drop_index(batch_op.f('ix_ocr_job_attach_id'))

    op.drop_table('ocr_job')
    op.drop_table('note_record_link')
    op.drop_table('treatment')
    with op.batch_alter_table('prescription_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_item_record_id'))

    op.drop_table('prescription_item')
    op.drop_table('learning_note')
    op.drop_table('attachment')
    op.drop_table('mentor_comment')
    with op.batch_alter_table('info_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_info_record_father_id'))

    op.drop_table('info_record')
    with op.batch_alter_table('dict_herb_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dict_herb_alias_herb_id'))
        batch_op.drop_index(batch_op.f('ix_dict_herb_alias_alias'))

    op.drop_table('dict_herb_alias')
    op.drop_table('dict_formula')
    op.drop_table('diagnosis')
    op.drop_table('case_narrative')
    op.drop_table('source_document')
    op.drop_table('mentor')
    op.drop_table('info_patient')
    with op.batch_alter_table('dict_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dict_term_term_type'))

    op.drop_table('dict_term')
    op.drop_table('dict_syndrome')
    op.drop_table('dict_herb')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_changed_at'))

    op.drop_table('audit_log')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
