"""Dictionary seed content for CASE.

This is a **starter set**, not a complete materia medica. It exists so the
archive is usable from day one and so autocomplete, name normalisation
and OCR misread correction have something to work against. The dictionary
is expected to grow as cases are entered — the schema never blocks a value
that is missing from it.

Content notes
-------------
* Herb names use the 《中国药典》 preferred form (生地黄 rather than 生地,
  黄芩 rather than 黄芩片). Prescription-style names and processed forms
  live in ``ALIASES`` and ``PROCESSED_HERBS``.
* ``alias_type`` follows 附表A4: 0 异名 / 1 简称 / 2 处方名 / 3 炮制品 /
  4 错写.
* Type-4 aliases are real OCR misreads observed on clinical scans, mostly
  visually similar characters. They are what lets the pipeline suggest
  黄芩 when the recogniser produced 黄苓.
* Syndrome names carry the 证 suffix, matching how the source documents
  write them.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# 中药基原药材
# --------------------------------------------------------------------------
HERBS: list[dict] = [
    # 解表药
    {"name": "麻黄", "pinyin": "ma huang", "category": "解表药", "nature": "温", "flavor": "辛,微苦", "meridians": "肺,膀胱", "functions": "发汗解表，宣肺平喘，利水消肿"},
    {"name": "桂枝", "pinyin": "gui zhi", "category": "解表药", "nature": "温", "flavor": "辛,甘", "meridians": "心,肺,膀胱", "functions": "发汗解肌，温通经脉，助阳化气"},
    {"name": "紫苏叶", "pinyin": "zi su ye", "category": "解表药", "nature": "温", "flavor": "辛", "meridians": "肺,脾", "functions": "解表散寒，行气和胃"},
    {"name": "生姜", "pinyin": "sheng jiang", "category": "解表药", "nature": "微温", "flavor": "辛", "meridians": "肺,脾,胃", "functions": "解表散寒，温中止呕，化痰止咳"},
    {"name": "荆芥", "pinyin": "jing jie", "category": "解表药", "nature": "微温", "flavor": "辛", "meridians": "肺,肝", "functions": "解表散风，透疹，消疮"},
    {"name": "防风", "pinyin": "fang feng", "category": "解表药", "nature": "微温", "flavor": "辛,甘", "meridians": "膀胱,肝,脾", "functions": "祛风解表，胜湿止痛，止痉"},
    {"name": "羌活", "pinyin": "qiang huo", "category": "解表药", "nature": "温", "flavor": "辛,苦", "meridians": "膀胱,肾", "functions": "解表散寒，祛风除湿，止痛"},
    {"name": "白芷", "pinyin": "bai zhi", "category": "解表药", "nature": "温", "flavor": "辛", "meridians": "胃,大肠,肺", "functions": "解表散寒，祛风止痛，宣通鼻窍，燥湿止带，消肿排脓"},
    {"name": "薄荷", "pinyin": "bo he", "category": "解表药", "nature": "凉", "flavor": "辛", "meridians": "肺,肝", "functions": "疏散风热，清利头目，利咽，透疹，疏肝行气"},
    {"name": "牛蒡子", "pinyin": "niu bang zi", "category": "解表药", "nature": "寒", "flavor": "辛,苦", "meridians": "肺,胃", "functions": "疏散风热，宣肺透疹，解毒利咽"},
    {"name": "蝉蜕", "pinyin": "chan tui", "category": "解表药", "nature": "寒", "flavor": "甘", "meridians": "肺,肝", "functions": "疏散风热，利咽透疹，明目退翳，解痉"},
    {"name": "桑叶", "pinyin": "sang ye", "category": "解表药", "nature": "寒", "flavor": "甘,苦", "meridians": "肺,肝", "functions": "疏散风热，清肺润燥，清肝明目"},
    {"name": "菊花", "pinyin": "ju hua", "category": "解表药", "nature": "微寒", "flavor": "甘,苦", "meridians": "肺,肝", "functions": "疏散风热，平肝明目，清热解毒"},
    {"name": "葛根", "pinyin": "ge gen", "category": "解表药", "nature": "凉", "flavor": "甘,辛", "meridians": "脾,胃,肺", "functions": "解肌退热，生津止渴，透疹，升阳止泻，通经活络，解酒毒"},
    {"name": "柴胡", "pinyin": "chai hu", "category": "解表药", "nature": "微寒", "flavor": "辛,苦", "meridians": "肝,胆,肺", "functions": "疏散退热，疏肝解郁，升举阳气"},
    {"name": "升麻", "pinyin": "sheng ma", "category": "解表药", "nature": "微寒", "flavor": "辛,微甘", "meridians": "肺,脾,胃,大肠", "functions": "发表透疹，清热解毒，升举阳气"},
    {"name": "淡豆豉", "pinyin": "dan dou chi", "category": "解表药", "nature": "凉", "flavor": "苦,辛", "meridians": "肺,胃", "functions": "解表，除烦，宣发郁热"},
    {"name": "浮萍", "pinyin": "fu ping", "category": "解表药", "nature": "寒", "flavor": "辛", "meridians": "肺", "functions": "宣散风热，透疹，利尿消肿"},

    # 清热药
    {"name": "石膏", "pinyin": "shi gao", "category": "清热药", "nature": "大寒", "flavor": "甘,辛", "meridians": "肺,胃", "functions": "清热泻火，除烦止渴"},
    {"name": "知母", "pinyin": "zhi mu", "category": "清热药", "nature": "寒", "flavor": "苦,甘", "meridians": "肺,胃,肾", "functions": "清热泻火，滋阴润燥"},
    {"name": "栀子", "pinyin": "zhi zi", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "心,肺,三焦", "functions": "泻火除烦，清热利湿，凉血解毒；外用消肿止痛"},
    {"name": "夏枯草", "pinyin": "xia ku cao", "category": "清热药", "nature": "寒", "flavor": "辛,苦", "meridians": "肝,胆", "functions": "清肝泻火，明目，散结消肿"},
    {"name": "黄芩", "pinyin": "huang qin", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "肺,胆,脾,大肠,小肠", "functions": "清热燥湿，泻火解毒，止血，安胎"},
    {"name": "黄连", "pinyin": "huang lian", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "心,脾,胃,肝,胆,大肠", "functions": "清热燥湿，泻火解毒"},
    {"name": "黄柏", "pinyin": "huang bai", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "肾,膀胱", "functions": "清热燥湿，泻火除蒸，解毒疗疮"},
    {"name": "龙胆", "pinyin": "long dan", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "肝,胆", "functions": "清热燥湿，泻肝胆火"},
    {"name": "苦参", "pinyin": "ku shen", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "心,肝,胃,大肠,膀胱", "functions": "清热燥湿，杀虫，利尿"},
    {"name": "金银花", "pinyin": "jin yin hua", "category": "清热药", "nature": "寒", "flavor": "甘", "meridians": "肺,心,胃", "functions": "清热解毒，疏散风热"},
    {"name": "连翘", "pinyin": "lian qiao", "category": "清热药", "nature": "微寒", "flavor": "苦", "meridians": "肺,心,小肠", "functions": "清热解毒，消肿散结，疏散风热"},
    {"name": "蒲公英", "pinyin": "pu gong ying", "category": "清热药", "nature": "寒", "flavor": "苦,甘", "meridians": "肝,胃", "functions": "清热解毒，消肿散结，利湿通淋"},
    {"name": "生地黄", "pinyin": "sheng di huang", "category": "清热药", "nature": "寒", "flavor": "甘", "meridians": "心,肝,肾", "functions": "清热凉血，养阴生津"},
    {"name": "玄参", "pinyin": "xuan shen", "category": "清热药", "nature": "微寒", "flavor": "甘,苦,咸", "meridians": "肺,胃,肾", "functions": "清热凉血，滋阴降火，解毒散结"},
    {"name": "牡丹皮", "pinyin": "mu dan pi", "category": "清热药", "nature": "微寒", "flavor": "苦,辛", "meridians": "心,肝,肾", "functions": "清热凉血，活血化瘀"},
    {"name": "赤芍", "pinyin": "chi shao", "category": "清热药", "nature": "微寒", "flavor": "苦", "meridians": "肝", "functions": "清热凉血，散瘀止痛"},
    {"name": "紫草", "pinyin": "zi cao", "category": "清热药", "nature": "寒", "flavor": "甘,咸", "meridians": "心,肝", "functions": "清热凉血，活血解毒，透疹消斑"},
    {"name": "板蓝根", "pinyin": "ban lan gen", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "心,胃", "functions": "清热解毒，凉血利咽"},
    {"name": "鱼腥草", "pinyin": "yu xing cao", "category": "清热药", "nature": "微寒", "flavor": "辛", "meridians": "肺", "functions": "清热解毒，消痈排脓，利尿通淋"},
    {"name": "败酱草", "pinyin": "bai jiang cao", "category": "清热药", "nature": "微寒", "flavor": "辛,苦", "meridians": "胃,大肠,肝", "functions": "清热解毒，消痈排脓，祛瘀止痛"},
    {"name": "白头翁", "pinyin": "bai tou weng", "category": "清热药", "nature": "寒", "flavor": "苦", "meridians": "胃,大肠", "functions": "清热解毒，凉血止痢"},
    {"name": "青蒿", "pinyin": "qing hao", "category": "清热药", "nature": "寒", "flavor": "苦,辛", "meridians": "肝,胆", "functions": "清虚热，除骨蒸，解暑热，截疟，退黄"},
    {"name": "地骨皮", "pinyin": "di gu pi", "category": "清热药", "nature": "寒", "flavor": "甘", "meridians": "肺,肝,肾", "functions": "凉血除蒸，清肺降火"},

    # 泻下药
    {"name": "大黄", "pinyin": "da huang", "category": "泻下药", "nature": "寒", "flavor": "苦", "meridians": "脾,胃,大肠,肝,心包", "functions": "泻下攻积，清热泻火，凉血解毒，逐瘀通经，利湿退黄"},
    {"name": "芒硝", "pinyin": "mang xiao", "category": "泻下药", "nature": "寒", "flavor": "咸,苦", "meridians": "胃,大肠", "functions": "泻下通便，润燥软坚，清火消肿"},
    {"name": "火麻仁", "pinyin": "huo ma ren", "category": "泻下药", "nature": "平", "flavor": "甘", "meridians": "脾,胃,大肠", "functions": "润肠通便"},

    # 祛风湿药
    {"name": "独活", "pinyin": "du huo", "category": "祛风湿药", "nature": "微温", "flavor": "辛,苦", "meridians": "肾,膀胱", "functions": "祛风除湿，通痹止痛"},
    {"name": "威灵仙", "pinyin": "wei ling xian", "category": "祛风湿药", "nature": "温", "flavor": "辛,咸", "meridians": "膀胱", "functions": "祛风湿，通经络，止痛"},
    {"name": "秦艽", "pinyin": "qin jiao", "category": "祛风湿药", "nature": "平", "flavor": "辛,苦", "meridians": "胃,肝,胆", "functions": "祛风湿，清湿热，止痹痛，退虚热"},
    {"name": "防己", "pinyin": "fang ji", "category": "祛风湿药", "nature": "寒", "flavor": "苦", "meridians": "膀胱,肺", "functions": "祛风止痛，利水消肿"},
    {"name": "桑寄生", "pinyin": "sang ji sheng", "category": "祛风湿药", "nature": "平", "flavor": "苦,甘", "meridians": "肝,肾", "functions": "祛风湿，补肝肾，强筋骨，安胎"},

    # 化湿药
    {"name": "藿香", "pinyin": "huo xiang", "category": "化湿药", "nature": "微温", "flavor": "辛", "meridians": "脾,胃,肺", "functions": "芳香化浊，和中止呕，发表解暑"},
    {"name": "佩兰", "pinyin": "pei lan", "category": "化湿药", "nature": "平", "flavor": "辛", "meridians": "脾,胃,肺", "functions": "芳香化湿，醒脾开胃，发表解暑"},
    {"name": "苍术", "pinyin": "cang zhu", "category": "化湿药", "nature": "温", "flavor": "辛,苦", "meridians": "脾,胃,肝", "functions": "燥湿健脾，祛风散寒，明目"},
    {"name": "厚朴", "pinyin": "hou po", "category": "化湿药", "nature": "温", "flavor": "苦,辛", "meridians": "脾,胃,肺,大肠", "functions": "燥湿消痰，下气除满"},
    {"name": "砂仁", "pinyin": "sha ren", "category": "化湿药", "nature": "温", "flavor": "辛", "meridians": "脾,胃,肾", "functions": "化湿开胃，温脾止泻，理气安胎"},

    # 利水渗湿药
    {"name": "茯苓", "pinyin": "fu ling", "category": "利水渗湿药", "nature": "平", "flavor": "甘,淡", "meridians": "心,肺,脾,肾", "functions": "利水渗湿，健脾，宁心"},
    {"name": "猪苓", "pinyin": "zhu ling", "category": "利水渗湿药", "nature": "平", "flavor": "甘,淡", "meridians": "肾,膀胱", "functions": "利水渗湿"},
    {"name": "泽泻", "pinyin": "ze xie", "category": "利水渗湿药", "nature": "寒", "flavor": "甘,淡", "meridians": "肾,膀胱", "functions": "利水渗湿，泄热，化浊降脂"},
    {"name": "薏苡仁", "pinyin": "yi yi ren", "category": "利水渗湿药", "nature": "凉", "flavor": "甘,淡", "meridians": "脾,胃,肺", "functions": "利水渗湿，健脾止泻，除痹，排脓，解毒散结"},
    {"name": "车前子", "pinyin": "che qian zi", "category": "利水渗湿药", "nature": "寒", "flavor": "甘", "meridians": "肝,肾,肺,小肠", "functions": "清热利尿通淋，渗湿止泻，明目，祛痰"},
    {"name": "滑石", "pinyin": "hua shi", "category": "利水渗湿药", "nature": "寒", "flavor": "甘,淡", "meridians": "膀胱,肺,胃", "functions": "利尿通淋，清热解暑；外用祛湿敛疮"},
    {"name": "木通", "pinyin": "mu tong", "category": "利水渗湿药", "nature": "寒", "flavor": "苦", "meridians": "心,小肠,膀胱", "functions": "利尿通淋，清心除烦，通经下乳"},
    {"name": "茵陈", "pinyin": "yin chen", "category": "利水渗湿药", "nature": "微寒", "flavor": "苦,辛", "meridians": "脾,胃,肝,胆", "functions": "清利湿热，利胆退黄"},
    {"name": "金钱草", "pinyin": "jin qian cao", "category": "利水渗湿药", "nature": "微寒", "flavor": "甘,咸", "meridians": "肝,胆,肾,膀胱", "functions": "利湿退黄，利尿通淋，解毒消肿"},

    # 温里药
    {"name": "附子", "pinyin": "fu zi", "category": "温里药", "nature": "大热", "flavor": "辛,甘", "meridians": "心,肾,脾", "functions": "回阳救逆，补火助阳，散寒止痛"},
    {"name": "干姜", "pinyin": "gan jiang", "category": "温里药", "nature": "热", "flavor": "辛", "meridians": "脾,胃,肾,心,肺", "functions": "温中散寒，回阳通脉，温肺化饮"},
    {"name": "肉桂", "pinyin": "rou gui", "category": "温里药", "nature": "大热", "flavor": "辛,甘", "meridians": "肾,脾,心,肝", "functions": "补火助阳，引火归元，散寒止痛，温通经脉"},
    {"name": "吴茱萸", "pinyin": "wu zhu yu", "category": "温里药", "nature": "热", "flavor": "辛,苦", "meridians": "肝,脾,胃,肾", "functions": "散寒止痛，降逆止呕，助阳止泻"},
    {"name": "花椒", "pinyin": "hua jiao", "category": "温里药", "nature": "温", "flavor": "辛", "meridians": "脾,胃,肾", "functions": "温中止痛，杀虫止痒"},

    # 理气药
    {"name": "陈皮", "pinyin": "chen pi", "category": "理气药", "nature": "温", "flavor": "苦,辛", "meridians": "肺,脾", "functions": "理气健脾，燥湿化痰"},
    {"name": "枳实", "pinyin": "zhi shi", "category": "理气药", "nature": "微寒", "flavor": "苦,辛,酸", "meridians": "脾,胃", "functions": "破气消积，化痰散痞"},
    {"name": "枳壳", "pinyin": "zhi ke", "category": "理气药", "nature": "微寒", "flavor": "苦,辛,酸", "meridians": "脾,胃", "functions": "理气宽中，行滞消胀"},
    {"name": "木香", "pinyin": "mu xiang", "category": "理气药", "nature": "温", "flavor": "辛,苦", "meridians": "脾,胃,大肠,三焦,胆", "functions": "行气止痛，健脾消食"},
    {"name": "香附", "pinyin": "xiang fu", "category": "理气药", "nature": "平", "flavor": "辛,微苦,微甘", "meridians": "肝,脾,三焦", "functions": "疏肝解郁，理气宽中，调经止痛"},
    {"name": "川楝子", "pinyin": "chuan lian zi", "category": "理气药", "nature": "寒", "flavor": "苦", "meridians": "肝,小肠,膀胱", "functions": "疏肝泄热，行气止痛，杀虫"},
    {"name": "乌药", "pinyin": "wu yao", "category": "理气药", "nature": "温", "flavor": "辛", "meridians": "肺,脾,肾,膀胱", "functions": "行气止痛，温肾散寒"},
    {"name": "薤白", "pinyin": "xie bai", "category": "理气药", "nature": "温", "flavor": "辛,苦", "meridians": "心,肺,胃,大肠", "functions": "通阳散结，行气导滞"},

    # 消食药
    {"name": "山楂", "pinyin": "shan zha", "category": "消食药", "nature": "微温", "flavor": "酸,甘", "meridians": "脾,胃,肝", "functions": "消食健胃，行气散瘀，化浊降脂"},
    {"name": "神曲", "pinyin": "shen qu", "category": "消食药", "nature": "温", "flavor": "甘,辛", "meridians": "脾,胃", "functions": "消食和胃"},
    {"name": "麦芽", "pinyin": "mai ya", "category": "消食药", "nature": "平", "flavor": "甘", "meridians": "脾,胃", "functions": "行气消食，健脾开胃，回乳消胀"},
    {"name": "鸡内金", "pinyin": "ji nei jin", "category": "消食药", "nature": "平", "flavor": "甘", "meridians": "脾,胃,小肠,膀胱", "functions": "健胃消食，涩精止遗，通淋化石"},

    # 驱虫药
    {"name": "槟榔", "pinyin": "bing lang", "category": "驱虫药", "nature": "温", "flavor": "苦,辛", "meridians": "胃,大肠", "functions": "杀虫消积，行气，利水，截疟"},

    # 止血药
    {"name": "三七", "pinyin": "san qi", "category": "止血药", "nature": "温", "flavor": "甘,微苦", "meridians": "肝,胃", "functions": "散瘀止血，消肿定痛"},
    {"name": "白及", "pinyin": "bai ji", "category": "止血药", "nature": "微寒", "flavor": "苦,甘,涩", "meridians": "肺,胃,肝", "functions": "收敛止血，消肿生肌"},
    {"name": "艾叶", "pinyin": "ai ye", "category": "止血药", "nature": "温", "flavor": "辛,苦", "meridians": "肝,脾,肾", "functions": "温经止血，散寒止痛；外用祛湿止痒"},

    # 活血化瘀药
    {"name": "川芎", "pinyin": "chuan xiong", "category": "活血化瘀药", "nature": "温", "flavor": "辛", "meridians": "肝,胆,心包", "functions": "活血行气，祛风止痛"},
    {"name": "延胡索", "pinyin": "yan hu suo", "category": "活血化瘀药", "nature": "温", "flavor": "辛,苦", "meridians": "肝,脾", "functions": "活血，行气，止痛"},
    {"name": "郁金", "pinyin": "yu jin", "category": "活血化瘀药", "nature": "寒", "flavor": "辛,苦", "meridians": "肝,心,肺", "functions": "活血止痛，行气解郁，清心凉血，利胆退黄"},
    {"name": "丹参", "pinyin": "dan shen", "category": "活血化瘀药", "nature": "微寒", "flavor": "苦", "meridians": "心,肝", "functions": "活血祛瘀，通经止痛，清心除烦，凉血消痈"},
    {"name": "桃仁", "pinyin": "tao ren", "category": "活血化瘀药", "nature": "平", "flavor": "苦,甘", "meridians": "心,肝,大肠", "functions": "活血祛瘀，润肠通便，止咳平喘"},
    {"name": "红花", "pinyin": "hong hua", "category": "活血化瘀药", "nature": "温", "flavor": "辛", "meridians": "心,肝", "functions": "活血通经，散瘀止痛"},
    {"name": "益母草", "pinyin": "yi mu cao", "category": "活血化瘀药", "nature": "微寒", "flavor": "苦,辛", "meridians": "肝,心包,膀胱", "functions": "活血调经，利尿消肿，清热解毒"},
    {"name": "牛膝", "pinyin": "niu xi", "category": "活血化瘀药", "nature": "平", "flavor": "苦,甘,酸", "meridians": "肝,肾", "functions": "逐瘀通经，补肝肾，强筋骨，利尿通淋，引血下行"},
    {"name": "莪术", "pinyin": "e zhu", "category": "活血化瘀药", "nature": "温", "flavor": "辛,苦", "meridians": "肝,脾", "functions": "行气破血，消积止痛"},
    {"name": "三棱", "pinyin": "san leng", "category": "活血化瘀药", "nature": "平", "flavor": "辛,苦", "meridians": "肝,脾", "functions": "破血行气，消积止痛"},
    {"name": "水蛭", "pinyin": "shui zhi", "category": "活血化瘀药", "nature": "平", "flavor": "咸,苦", "meridians": "肝", "functions": "破血通经，逐瘀消癥"},

    # 化痰止咳平喘药
    {"name": "半夏", "pinyin": "ban xia", "category": "化痰止咳平喘药", "nature": "温", "flavor": "辛", "meridians": "脾,胃,肺", "functions": "燥湿化痰，降逆止呕，消痞散结"},
    {"name": "天南星", "pinyin": "tian nan xing", "category": "化痰止咳平喘药", "nature": "温", "flavor": "苦,辛", "meridians": "肺,肝,脾", "functions": "散结消肿；外用治痈肿"},
    {"name": "胆南星", "pinyin": "dan nan xing", "category": "化痰止咳平喘药", "nature": "凉", "flavor": "苦,微辛", "meridians": "肺,肝,脾", "functions": "清热化痰，息风定惊"},
    {"name": "桔梗", "pinyin": "jie geng", "category": "化痰止咳平喘药", "nature": "平", "flavor": "苦,辛", "meridians": "肺", "functions": "宣肺，利咽，祛痰，排脓"},
    {"name": "川贝母", "pinyin": "chuan bei mu", "category": "化痰止咳平喘药", "nature": "微寒", "flavor": "苦,甘", "meridians": "肺,心", "functions": "清热润肺，化痰止咳，散结消痈"},
    {"name": "浙贝母", "pinyin": "zhe bei mu", "category": "化痰止咳平喘药", "nature": "寒", "flavor": "苦", "meridians": "肺,心", "functions": "清热化痰止咳，解毒散结消痈"},
    {"name": "瓜蒌", "pinyin": "gua lou", "category": "化痰止咳平喘药", "nature": "寒", "flavor": "甘,微苦", "meridians": "肺,胃,大肠", "functions": "清热涤痰，宽胸散结，润燥滑肠"},
    {"name": "竹茹", "pinyin": "zhu ru", "category": "化痰止咳平喘药", "nature": "微寒", "flavor": "甘", "meridians": "肺,胃,心,胆", "functions": "清热化痰，除烦，止呕"},
    {"name": "苦杏仁", "pinyin": "ku xing ren", "category": "化痰止咳平喘药", "nature": "微温", "flavor": "苦", "meridians": "肺,大肠", "functions": "降气止咳平喘，润肠通便"},
    {"name": "紫菀", "pinyin": "zi wan", "category": "化痰止咳平喘药", "nature": "温", "flavor": "辛,苦", "meridians": "肺", "functions": "润肺下气，消痰止咳"},
    {"name": "款冬花", "pinyin": "kuan dong hua", "category": "化痰止咳平喘药", "nature": "温", "flavor": "辛,微苦", "meridians": "肺", "functions": "润肺下气，止咳化痰"},
    {"name": "桑白皮", "pinyin": "sang bai pi", "category": "化痰止咳平喘药", "nature": "寒", "flavor": "甘", "meridians": "肺", "functions": "泻肺平喘，利水消肿"},
    {"name": "葶苈子", "pinyin": "ting li zi", "category": "化痰止咳平喘药", "nature": "大寒", "flavor": "辛,苦", "meridians": "肺,膀胱", "functions": "泻肺平喘，行水消肿"},
    {"name": "旋覆花", "pinyin": "xuan fu hua", "category": "化痰止咳平喘药", "nature": "微温", "flavor": "苦,辛,咸", "meridians": "肺,脾,胃,大肠", "functions": "降气，消痰，行水，止呕"},
    {"name": "枇杷叶", "pinyin": "pi pa ye", "category": "化痰止咳平喘药", "nature": "微寒", "flavor": "苦", "meridians": "肺,胃", "functions": "清肺止咳，降逆止呕"},

    # 安神药
    {"name": "酸枣仁", "pinyin": "suan zao ren", "category": "安神药", "nature": "平", "flavor": "甘,酸", "meridians": "肝,胆,心", "functions": "养心补肝，宁心安神，敛汗，生津"},
    {"name": "柏子仁", "pinyin": "bai zi ren", "category": "安神药", "nature": "平", "flavor": "甘", "meridians": "心,肾,大肠", "functions": "养心安神，润肠通便，止汗"},
    {"name": "远志", "pinyin": "yuan zhi", "category": "安神药", "nature": "温", "flavor": "苦,辛", "meridians": "心,肾,肺", "functions": "安神益智，交通心肾，祛痰，消肿"},
    {"name": "龙骨", "pinyin": "long gu", "category": "安神药", "nature": "平", "flavor": "甘,涩", "meridians": "心,肝,肾", "functions": "镇惊安神，敛汗固精；外用生肌敛疮"},
    {"name": "牡蛎", "pinyin": "mu li", "category": "安神药", "nature": "微寒", "flavor": "咸", "meridians": "肝,胆,肾", "functions": "重镇安神，潜阳补阴，软坚散结"},

    # 平肝息风药
    {"name": "天麻", "pinyin": "tian ma", "category": "平肝息风药", "nature": "平", "flavor": "甘", "meridians": "肝", "functions": "息风止痉，平抑肝阳，祛风通络"},
    {"name": "钩藤", "pinyin": "gou teng", "category": "平肝息风药", "nature": "凉", "flavor": "甘", "meridians": "肝,心包", "functions": "息风定惊，清热平肝"},
    {"name": "石决明", "pinyin": "shi jue ming", "category": "平肝息风药", "nature": "寒", "flavor": "咸", "meridians": "肝", "functions": "平肝潜阳，清肝明目"},
    {"name": "全蝎", "pinyin": "quan xie", "category": "平肝息风药", "nature": "平", "flavor": "辛", "meridians": "肝", "functions": "息风镇痉，通络止痛，攻毒散结"},
    {"name": "僵蚕", "pinyin": "jiang can", "category": "平肝息风药", "nature": "平", "flavor": "咸,辛", "meridians": "肝,肺,胃", "functions": "息风止痉，祛风止痛，化痰散结"},

    # 补虚药
    {"name": "人参", "pinyin": "ren shen", "category": "补虚药", "nature": "微温", "flavor": "甘,微苦", "meridians": "脾,肺,心,肾", "functions": "大补元气，复脉固脱，补脾益肺，生津养血，安神益智"},
    {"name": "党参", "pinyin": "dang shen", "category": "补虚药", "nature": "平", "flavor": "甘", "meridians": "脾,肺", "functions": "健脾益肺，养血生津"},
    {"name": "黄芪", "pinyin": "huang qi", "category": "补虚药", "nature": "微温", "flavor": "甘", "meridians": "肺,脾", "functions": "补气升阳，固表止汗，利水消肿，生津养血，行滞通痹，托毒排脓，敛疮生肌"},
    {"name": "白术", "pinyin": "bai zhu", "category": "补虚药", "nature": "温", "flavor": "苦,甘", "meridians": "脾,胃", "functions": "健脾益气，燥湿利水，止汗，安胎"},
    {"name": "山药", "pinyin": "shan yao", "category": "补虚药", "nature": "平", "flavor": "甘", "meridians": "脾,肺,肾", "functions": "补脾养胃，生津益肺，补肾涩精"},
    {"name": "甘草", "pinyin": "gan cao", "category": "补虚药", "nature": "平", "flavor": "甘", "meridians": "心,肺,脾,胃", "functions": "补脾益气，清热解毒，祛痰止咳，缓急止痛，调和诸药"},
    {"name": "当归", "pinyin": "dang gui", "category": "补虚药", "nature": "温", "flavor": "甘,辛", "meridians": "肝,心,脾", "functions": "补血活血，调经止痛，润肠通便"},
    {"name": "熟地黄", "pinyin": "shu di huang", "category": "补虚药", "nature": "微温", "flavor": "甘", "meridians": "肝,肾", "functions": "补血滋阴，益精填髓"},
    {"name": "白芍", "pinyin": "bai shao", "category": "补虚药", "nature": "微寒", "flavor": "苦,酸", "meridians": "肝,脾", "functions": "养血调经，敛阴止汗，柔肝止痛，平抑肝阳"},
    {"name": "阿胶", "pinyin": "e jiao", "category": "补虚药", "nature": "平", "flavor": "甘", "meridians": "肺,肝,肾", "functions": "补血滋阴，润燥，止血"},
    {"name": "何首乌", "pinyin": "he shou wu", "category": "补虚药", "nature": "微温", "flavor": "苦,甘,涩", "meridians": "肝,心,肾", "functions": "解毒，消痈，截疟，润肠通便"},
    {"name": "枸杞子", "pinyin": "gou qi zi", "category": "补虚药", "nature": "平", "flavor": "甘", "meridians": "肝,肾", "functions": "滋补肝肾，益精明目"},
    {"name": "麦冬", "pinyin": "mai dong", "category": "补虚药", "nature": "微寒", "flavor": "甘,微苦", "meridians": "心,肺,胃", "functions": "养阴生津，润肺清心"},
    {"name": "北沙参", "pinyin": "bei sha shen", "category": "补虚药", "nature": "微寒", "flavor": "甘", "meridians": "肺,胃", "functions": "养阴清肺，益胃生津"},
    {"name": "玉竹", "pinyin": "yu zhu", "category": "补虚药", "nature": "微寒", "flavor": "甘", "meridians": "肺,胃", "functions": "养阴润燥，生津止渴"},
    {"name": "女贞子", "pinyin": "nv zhen zi", "category": "补虚药", "nature": "凉", "flavor": "甘,苦", "meridians": "肝,肾", "functions": "滋补肝肾，明目乌发"},
    {"name": "杜仲", "pinyin": "du zhong", "category": "补虚药", "nature": "温", "flavor": "甘", "meridians": "肝,肾", "functions": "补肝肾，强筋骨，安胎"},
    {"name": "淫羊藿", "pinyin": "yin yang huo", "category": "补虚药", "nature": "温", "flavor": "辛,甘", "meridians": "肝,肾", "functions": "补肾阳，强筋骨，祛风湿"},
    {"name": "巴戟天", "pinyin": "ba ji tian", "category": "补虚药", "nature": "微温", "flavor": "甘,辛", "meridians": "肾,肝", "functions": "补肾阳，强筋骨，祛风湿"},
    {"name": "菟丝子", "pinyin": "tu si zi", "category": "补虚药", "nature": "平", "flavor": "甘", "meridians": "肝,肾,脾", "functions": "补益肝肾，固精缩尿，安胎，明目，止泻"},

    # 收涩药
    {"name": "五味子", "pinyin": "wu wei zi", "category": "收涩药", "nature": "温", "flavor": "酸,甘", "meridians": "肺,心,肾", "functions": "收敛固涩，益气生津，补肾宁心"},
    {"name": "山茱萸", "pinyin": "shan zhu yu", "category": "收涩药", "nature": "微温", "flavor": "酸,涩", "meridians": "肝,肾", "functions": "补益肝肾，收涩固脱"},
    {"name": "乌梅", "pinyin": "wu mei", "category": "收涩药", "nature": "平", "flavor": "酸,涩", "meridians": "肝,脾,肺,大肠", "functions": "敛肺，涩肠，生津，安蛔"},
    {"name": "莲子", "pinyin": "lian zi", "category": "收涩药", "nature": "平", "flavor": "甘,涩", "meridians": "脾,肾,心", "functions": "补脾止泻，止带，益肾涩精，养心安神"},
    {"name": "莲子心", "pinyin": "lian zi xin", "category": "安神药", "nature": "寒", "flavor": "苦", "meridians": "心,肾", "functions": "清心安神，交通心肾，涩精止血"},
]

# --------------------------------------------------------------------------
# 炮制品：各自成为字典条目并指向基原
# --------------------------------------------------------------------------
PROCESSED_HERBS: list[dict] = [
    {"herb": "黄芩片", "parent": "黄芩", "processing": "切片"},
    {"herb": "炒黄芩", "parent": "黄芩", "processing": "清炒"},
    {"herb": "酒黄连", "parent": "黄连", "processing": "酒炙"},
    {"herb": "姜黄连", "parent": "黄连", "processing": "姜汁炙"},
    {"herb": "盐黄柏", "parent": "黄柏", "processing": "盐炙"},
    {"herb": "醋柴胡", "parent": "柴胡", "processing": "醋炙"},
    {"herb": "醋香附", "parent": "香附", "processing": "醋炙"},
    {"herb": "醋延胡索", "parent": "延胡索", "processing": "醋炙"},
    {"herb": "醋莪术", "parent": "莪术", "processing": "醋炙"},
    {"herb": "醋三棱", "parent": "三棱", "processing": "醋炙"},
    {"herb": "炒酸枣仁", "parent": "酸枣仁", "processing": "清炒"},
    {"herb": "砂烫枳实", "parent": "枳实", "processing": "砂烫"},
    {"herb": "麸炒枳壳", "parent": "枳壳", "processing": "麸炒"},
    {"herb": "炒牛蒡子", "parent": "牛蒡子", "processing": "清炒"},
    {"herb": "煅龙骨", "parent": "龙骨", "processing": "煅制"},
    {"herb": "煅牡蛎", "parent": "牡蛎", "processing": "煅制"},
    {"herb": "煅石膏", "parent": "石膏", "processing": "煅制"},
    {"herb": "炒白术", "parent": "白术", "processing": "清炒"},
    {"herb": "焦白术", "parent": "白术", "processing": "炒焦"},
    {"herb": "土炒白术", "parent": "白术", "processing": "土炒"},
    {"herb": "蜜炙黄芪", "parent": "黄芪", "processing": "蜜炙"},
    {"herb": "炙甘草", "parent": "甘草", "processing": "蜜炙"},
    {"herb": "甘草片", "parent": "甘草", "processing": "切片"},
    {"herb": "炒麦芽", "parent": "麦芽", "processing": "清炒"},
    {"herb": "焦山楂", "parent": "山楂", "processing": "炒焦"},
    {"herb": "炒神曲", "parent": "神曲", "processing": "清炒"},
    {"herb": "法半夏", "parent": "半夏", "processing": "炮制"},
    {"herb": "姜半夏", "parent": "半夏", "processing": "姜制"},
    {"herb": "清半夏", "parent": "半夏", "processing": "矾制"},
    {"herb": "制天南星", "parent": "天南星", "processing": "炮制"},
    {"herb": "制何首乌", "parent": "何首乌", "processing": "炮制"},
    {"herb": "酒当归", "parent": "当归", "processing": "酒炙"},
    {"herb": "酒白芍", "parent": "白芍", "processing": "酒炙"},
    {"herb": "炒白芍", "parent": "白芍", "processing": "清炒"},
    {"herb": "盐杜仲", "parent": "杜仲", "processing": "盐炙"},
    {"herb": "盐车前子", "parent": "车前子", "processing": "盐炙"},
    {"herb": "盐知母", "parent": "知母", "processing": "盐炙"},
    {"herb": "蜜炙麻黄", "parent": "麻黄", "processing": "蜜炙"},
    {"herb": "蜜炙枇杷叶", "parent": "枇杷叶", "processing": "蜜炙"},
    {"herb": "炒苦杏仁", "parent": "苦杏仁", "processing": "清炒"},
    {"herb": "炒桃仁", "parent": "桃仁", "processing": "清炒"},
    {"herb": "酒大黄", "parent": "大黄", "processing": "酒炙"},
    {"herb": "熟大黄", "parent": "大黄", "processing": "酒蒸"},
    {"herb": "大黄炭", "parent": "大黄", "processing": "炒炭"},
    {"herb": "麸炒苍术", "parent": "苍术", "processing": "麸炒"},
    {"herb": "炒薏苡仁", "parent": "薏苡仁", "processing": "清炒"},
    {"herb": "麸炒山药", "parent": "山药", "processing": "麸炒"},
]

# --------------------------------------------------------------------------
# 中药别名
# --------------------------------------------------------------------------
ALIASES: list[dict] = [
    # --- 处方名 / 简称 ---
    {"herb": "生地黄", "alias": "生地", "alias_type": 2},
    {"herb": "熟地黄", "alias": "熟地", "alias_type": 2},
    {"herb": "熟地黄", "alias": "大熟地", "alias_type": 2},
    {"herb": "白芍", "alias": "杭白芍", "alias_type": 2},
    {"herb": "白芍", "alias": "白芍药", "alias_type": 0},
    {"herb": "当归", "alias": "全当归", "alias_type": 2},
    {"herb": "黄芪", "alias": "生黄芪", "alias_type": 2},
    {"herb": "黄芪", "alias": "北芪", "alias_type": 0},
    {"herb": "黄芪", "alias": "绵黄芪", "alias_type": 0},
    {"herb": "党参", "alias": "潞党参", "alias_type": 2},
    {"herb": "甘草", "alias": "生甘草", "alias_type": 2},
    {"herb": "甘草", "alias": "国老", "alias_type": 0},
    {"herb": "牛膝", "alias": "怀牛膝", "alias_type": 2},
    {"herb": "杜仲", "alias": "川杜仲", "alias_type": 2},
    {"herb": "枸杞子", "alias": "枸杞", "alias_type": 1},
    {"herb": "枸杞子", "alias": "甘杞子", "alias_type": 2},
    {"herb": "北沙参", "alias": "沙参", "alias_type": 1},
    {"herb": "菟丝子", "alias": "菟丝", "alias_type": 1},
    {"herb": "女贞子", "alias": "女贞", "alias_type": 1},
    {"herb": "山茱萸", "alias": "山萸肉", "alias_type": 2},
    {"herb": "山茱萸", "alias": "萸肉", "alias_type": 1},
    {"herb": "五味子", "alias": "北五味", "alias_type": 2},
    {"herb": "五味子", "alias": "辽五味", "alias_type": 2},
    {"herb": "酸枣仁", "alias": "枣仁", "alias_type": 1},
    {"herb": "柏子仁", "alias": "柏子", "alias_type": 1},
    {"herb": "远志", "alias": "远志肉", "alias_type": 2},
    {"herb": "鸡内金", "alias": "内金", "alias_type": 1},
    {"herb": "延胡索", "alias": "元胡", "alias_type": 0},
    {"herb": "延胡索", "alias": "玄胡索", "alias_type": 0},
    {"herb": "郁金", "alias": "玉金", "alias_type": 0},
    {"herb": "牡丹皮", "alias": "丹皮", "alias_type": 1},
    {"herb": "地骨皮", "alias": "骨皮", "alias_type": 1},
    {"herb": "板蓝根", "alias": "蓝根", "alias_type": 1},
    {"herb": "蒲公英", "alias": "公英", "alias_type": 1},
    {"herb": "夏枯草", "alias": "夏枯球", "alias_type": 0},
    {"herb": "龙胆", "alias": "龙胆草", "alias_type": 0},
    {"herb": "藿香", "alias": "广藿香", "alias_type": 2},
    {"herb": "佩兰", "alias": "兰草", "alias_type": 0},
    {"herb": "苍术", "alias": "茅术", "alias_type": 0},
    {"herb": "厚朴", "alias": "川朴", "alias_type": 2},
    {"herb": "砂仁", "alias": "缩砂仁", "alias_type": 0},
    {"herb": "泽泻", "alias": "建泽泻", "alias_type": 2},
    {"herb": "车前子", "alias": "车前", "alias_type": 1},
    {"herb": "茵陈", "alias": "茵陈蒿", "alias_type": 0},
    {"herb": "金钱草", "alias": "过路黄", "alias_type": 0},
    {"herb": "茯苓", "alias": "云苓", "alias_type": 0},
    {"herb": "茯苓", "alias": "白茯苓", "alias_type": 0},
    {"herb": "薏苡仁", "alias": "苡仁", "alias_type": 1},
    {"herb": "薏苡仁", "alias": "薏米", "alias_type": 0},
    {"herb": "附子", "alias": "附片", "alias_type": 2},
    {"herb": "附子", "alias": "制附子", "alias_type": 2},
    {"herb": "干姜", "alias": "白姜", "alias_type": 0},
    {"herb": "肉桂", "alias": "桂皮", "alias_type": 0},
    {"herb": "吴茱萸", "alias": "吴萸", "alias_type": 1},
    {"herb": "陈皮", "alias": "橘皮", "alias_type": 0},
    {"herb": "枳实", "alias": "江枳实", "alias_type": 2},
    {"herb": "枳壳", "alias": "江枳壳", "alias_type": 2},
    {"herb": "木香", "alias": "广木香", "alias_type": 2},
    {"herb": "木香", "alias": "云木香", "alias_type": 0},
    {"herb": "香附", "alias": "香附子", "alias_type": 0},
    {"herb": "乌药", "alias": "台乌", "alias_type": 2},
    {"herb": "山楂", "alias": "山楂肉", "alias_type": 2},
    {"herb": "麦芽", "alias": "大麦芽", "alias_type": 0},
    {"herb": "三七", "alias": "田七", "alias_type": 0},
    {"herb": "三七", "alias": "参三七", "alias_type": 0},
    {"herb": "川芎", "alias": "芎䓖", "alias_type": 0},
    {"herb": "丹参", "alias": "紫丹参", "alias_type": 2},
    {"herb": "桃仁", "alias": "光桃仁", "alias_type": 2},
    {"herb": "红花", "alias": "草红花", "alias_type": 2},
    {"herb": "益母草", "alias": "坤草", "alias_type": 0},
    {"herb": "牛膝", "alias": "牛七", "alias_type": 0},
    {"herb": "桔梗", "alias": "苦桔梗", "alias_type": 2},
    {"herb": "瓜蒌", "alias": "栝楼", "alias_type": 0},
    {"herb": "瓜蒌", "alias": "全瓜蒌", "alias_type": 2},
    {"herb": "苦杏仁", "alias": "杏仁", "alias_type": 1},
    {"herb": "款冬花", "alias": "冬花", "alias_type": 1},
    {"herb": "桑白皮", "alias": "桑皮", "alias_type": 1},
    {"herb": "川贝母", "alias": "川贝", "alias_type": 1,
     "ambiguity_note": "“川贝”可能指多种贝母，需人工确认"},
    {"herb": "浙贝母", "alias": "浙贝", "alias_type": 1},
    {"herb": "天麻", "alias": "明天麻", "alias_type": 2},
    {"herb": "钩藤", "alias": "双钩藤", "alias_type": 0},
    {"herb": "僵蚕", "alias": "白僵蚕", "alias_type": 0},
    {"herb": "牡蛎", "alias": "生牡蛎", "alias_type": 2},
    {"herb": "龙骨", "alias": "生龙骨", "alias_type": 2},
    {"herb": "石膏", "alias": "生石膏", "alias_type": 2},
    {"herb": "知母", "alias": "肥知母", "alias_type": 2},
    {"herb": "栀子", "alias": "山栀", "alias_type": 0},
    {"herb": "黄连", "alias": "川连", "alias_type": 2},
    {"herb": "金银花", "alias": "双花", "alias_type": 0},
    {"herb": "金银花", "alias": "忍冬花", "alias_type": 0},
    {"herb": "玄参", "alias": "元参", "alias_type": 0},
    {"herb": "麦冬", "alias": "麦门冬", "alias_type": 0},
    {"herb": "玉竹", "alias": "葳蕤", "alias_type": 0},
    {"herb": "淫羊藿", "alias": "仙灵脾", "alias_type": 0},
    {"herb": "乌梅", "alias": "梅实", "alias_type": 0},
    {"herb": "莲子", "alias": "莲子肉", "alias_type": 2},
    {"herb": "白芷", "alias": "香白芷", "alias_type": 2},
    {"herb": "羌活", "alias": "川羌活", "alias_type": 2},
    {"herb": "防风", "alias": "北防风", "alias_type": 2},
    {"herb": "荆芥", "alias": "荆芥穗", "alias_type": 2},
    {"herb": "葛根", "alias": "粉葛根", "alias_type": 2},
    {"herb": "升麻", "alias": "绿升麻", "alias_type": 2},
    {"herb": "半夏", "alias": "制半夏", "alias_type": 2},
    {"herb": "半夏", "alias": "法夏", "alias_type": 1},

    # --- 错写：真实扫描中出现的 OCR 形近字误识 ---
    {"herb": "黄芩", "alias": "黄苓", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：苓/芩"},
    {"herb": "黄连", "alias": "黄莲", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：莲/连"},
    {"herb": "黄柏", "alias": "盐黄相", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：相/柏"},
    {"herb": "莪术", "alias": "获术", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：获/莪"},
    {"herb": "苦参", "alias": "古参", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：古/苦"},
    {"herb": "苦参", "alias": "苦參", "alias_type": 4,
     "ambiguity_note": "OCR 繁简混杂"},
    {"herb": "紫菀", "alias": "紫苑", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：苑/菀"},
    {"herb": "栀子", "alias": "枝子", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：枝/栀"},
    {"herb": "薄荷", "alias": "卜荷", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：卜/薄"},
    {"herb": "山楂", "alias": "山查", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：查/楂"},
    {"herb": "枳实", "alias": "积实", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：积/枳"},
    {"herb": "枳壳", "alias": "积壳", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：积/枳"},
    {"herb": "川芎", "alias": "川弓", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：弓/芎"},
    {"herb": "茯苓", "alias": "伏苓", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：伏/茯"},
    {"herb": "薏苡仁", "alias": "薏以仁", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：以/苡"},
    {"herb": "金银花", "alias": "金很花", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：很/银"},
    {"herb": "柴胡", "alias": "紫胡", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：紫/柴"},
    {"herb": "白芍", "alias": "白苟", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：苟/芍"},
    {"herb": "甘草", "alias": "干草", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：干/甘"},
    {"herb": "桂枝", "alias": "桂支", "alias_type": 4,
     "ambiguity_note": "OCR 形近字误识：支/枝"},
]

# --------------------------------------------------------------------------
# 证型
# --------------------------------------------------------------------------
SYNDROMES: list[dict] = [
    # 脾胃
    {"name": "肝胃不和证", "category": "脏腑辨证", "key_symptoms": "胃脘胀痛，嗳气，情志不畅则加重，脉弦", "treatment": "疏肝理气和胃", "common_formula": "柴胡疏肝散"},
    {"name": "脾胃虚弱证", "category": "脏腑辨证", "key_symptoms": "食少便溏，脘腹隐痛，神疲乏力", "treatment": "健脾益气", "common_formula": "四君子汤"},
    {"name": "脾胃虚寒证", "category": "脏腑辨证", "key_symptoms": "脘腹冷痛喜温喜按，便溏，舌淡", "treatment": "温中健脾", "common_formula": "理中丸"},
    {"name": "湿热蕴脾证", "category": "脏腑辨证", "key_symptoms": "脘腹痞闷，口苦口黏，苔黄腻", "treatment": "清热化湿", "common_formula": "连朴饮"},
    {"name": "寒湿困脾证", "category": "脏腑辨证", "key_symptoms": "脘腹痞闷，头身困重，苔白腻", "treatment": "温中化湿", "common_formula": "胃苓汤"},
    {"name": "胃阴虚证", "category": "脏腑辨证", "key_symptoms": "胃脘灼痛，饥不欲食，口燥咽干", "treatment": "养阴益胃", "common_formula": "益胃汤"},
    {"name": "胃火炽盛证", "category": "脏腑辨证", "key_symptoms": "胃脘灼痛，渴喜冷饮，口臭", "treatment": "清胃泻火", "common_formula": "清胃散"},
    {"name": "食滞胃脘证", "category": "脏腑辨证", "key_symptoms": "脘腹胀满，嗳腐吞酸", "treatment": "消食导滞", "common_formula": "保和丸"},
    {"name": "脾虚湿盛证", "category": "脏腑辨证", "key_symptoms": "食少便溏，肢体困重，苔白腻", "treatment": "健脾利湿", "common_formula": "参苓白术散"},

    # 肝胆
    {"name": "肝气郁结证", "category": "脏腑辨证", "key_symptoms": "情志抑郁，胸胁胀满，善太息", "treatment": "疏肝解郁", "common_formula": "柴胡疏肝散"},
    {"name": "肝火上炎证", "category": "脏腑辨证", "key_symptoms": "头痛目赤，口苦，急躁易怒", "treatment": "清肝泻火", "common_formula": "龙胆泻肝汤"},
    {"name": "肝阳上亢证", "category": "脏腑辨证", "key_symptoms": "头目胀痛，眩晕，腰膝酸软", "treatment": "平肝潜阳", "common_formula": "天麻钩藤饮"},
    {"name": "肝血虚证", "category": "脏腑辨证", "key_symptoms": "眩晕，视物模糊，肢体麻木", "treatment": "补血养肝", "common_formula": "四物汤"},
    {"name": "肝阴虚证", "category": "脏腑辨证", "key_symptoms": "头晕耳鸣，两目干涩，五心烦热", "treatment": "滋阴养肝", "common_formula": "一贯煎"},
    {"name": "肝胆湿热证", "category": "脏腑辨证", "key_symptoms": "胁肋胀痛，口苦，身目发黄", "treatment": "清利肝胆湿热", "common_formula": "龙胆泻肝汤"},
    {"name": "胆郁痰扰证", "category": "脏腑辨证", "key_symptoms": "惊悸不宁，烦躁失眠，苔黄腻", "treatment": "清热化痰", "common_formula": "黄连温胆汤"},

    # 心
    {"name": "心气虚证", "category": "脏腑辨证", "key_symptoms": "心悸气短，动则加重，神疲", "treatment": "益气养心", "common_formula": "养心汤"},
    {"name": "心血虚证", "category": "脏腑辨证", "key_symptoms": "心悸失眠，健忘，面色淡白", "treatment": "养血安神", "common_formula": "归脾汤"},
    {"name": "心阴虚证", "category": "脏腑辨证", "key_symptoms": "心悸失眠，五心烦热，盗汗", "treatment": "滋阴养心", "common_formula": "天王补心丹"},
    {"name": "心阳虚证", "category": "脏腑辨证", "key_symptoms": "心悸怔忡，胸闷气短，形寒肢冷", "treatment": "温补心阳", "common_formula": "桂枝甘草汤"},
    {"name": "心火亢盛证", "category": "脏腑辨证", "key_symptoms": "心烦失眠，口舌生疮，小便短赤", "treatment": "清心泻火", "common_formula": "导赤散"},
    {"name": "心血瘀阻证", "category": "脏腑辨证", "key_symptoms": "心胸刺痛，痛引肩背，舌紫暗", "treatment": "活血化瘀，通脉止痛", "common_formula": "血府逐瘀汤"},
    {"name": "痰火扰心证", "category": "脏腑辨证", "key_symptoms": "心烦失眠，痰多，甚则狂躁", "treatment": "清心豁痰", "common_formula": "礞石滚痰丸"},

    # 肺
    {"name": "风寒犯肺证", "category": "脏腑辨证", "key_symptoms": "咳嗽痰白稀，鼻塞流清涕", "treatment": "疏风散寒，宣肺止咳", "common_formula": "三拗汤"},
    {"name": "风热犯肺证", "category": "脏腑辨证", "key_symptoms": "咳嗽痰黄稠，咽痛，发热微恶风", "treatment": "疏风清热，宣肺止咳", "common_formula": "桑菊饮"},
    {"name": "燥邪伤肺证", "category": "脏腑辨证", "key_symptoms": "干咳无痰，鼻咽干燥", "treatment": "清燥润肺", "common_formula": "桑杏汤"},
    {"name": "肺气虚证", "category": "脏腑辨证", "key_symptoms": "咳喘无力，气短，易感冒", "treatment": "补益肺气", "common_formula": "补肺汤"},
    {"name": "肺阴虚证", "category": "脏腑辨证", "key_symptoms": "干咳少痰，咽干，潮热盗汗", "treatment": "滋阴润肺", "common_formula": "百合固金汤"},
    {"name": "痰湿阻肺证", "category": "脏腑辨证", "key_symptoms": "咳嗽痰多色白易咯，胸闷", "treatment": "燥湿化痰", "common_formula": "二陈汤"},
    {"name": "痰热壅肺证", "category": "脏腑辨证", "key_symptoms": "咳嗽痰黄稠，胸闷气促", "treatment": "清热化痰", "common_formula": "清金化痰汤"},

    # 肾
    {"name": "肾阳虚证", "category": "脏腑辨证", "key_symptoms": "腰膝酸冷，畏寒肢冷，夜尿多", "treatment": "温补肾阳", "common_formula": "金匮肾气丸"},
    {"name": "肾阴虚证", "category": "脏腑辨证", "key_symptoms": "腰膝酸软，五心烦热，盗汗", "treatment": "滋补肾阴", "common_formula": "六味地黄丸"},
    {"name": "肾气虚证", "category": "脏腑辨证", "key_symptoms": "腰膝酸软，小便频数，余沥不尽", "treatment": "补肾益气", "common_formula": "金匮肾气丸"},
    {"name": "肾精不足证", "category": "脏腑辨证", "key_symptoms": "小儿发育迟缓，成人早衰健忘", "treatment": "补益肾精", "common_formula": "河车大造丸"},
    {"name": "肾虚水泛证", "category": "脏腑辨证", "key_symptoms": "水肿下肢为甚，腰膝酸冷", "treatment": "温阳利水", "common_formula": "真武汤"},

    # 气血津液
    {"name": "气虚证", "category": "气血津液辨证", "key_symptoms": "神疲乏力，少气懒言，自汗", "treatment": "补气", "common_formula": "四君子汤"},
    {"name": "血虚证", "category": "气血津液辨证", "key_symptoms": "面色淡白，唇甲色淡，头晕", "treatment": "补血", "common_formula": "四物汤"},
    {"name": "气血两虚证", "category": "气血津液辨证", "key_symptoms": "气虚与血虚并见", "treatment": "益气养血", "common_formula": "八珍汤"},
    {"name": "气滞证", "category": "气血津液辨证", "key_symptoms": "胀闷疼痛，部位走窜", "treatment": "行气", "common_formula": "五磨饮子"},
    {"name": "血瘀证", "category": "气血津液辨证", "key_symptoms": "刺痛固定，舌紫暗有瘀斑", "treatment": "活血化瘀", "common_formula": "桃红四物汤"},
    {"name": "气滞血瘀证", "category": "气血津液辨证", "key_symptoms": "胀痛与刺痛并见，舌紫暗", "treatment": "行气活血", "common_formula": "血府逐瘀汤"},
    {"name": "气虚血瘀证", "category": "气血津液辨证", "key_symptoms": "乏力与刺痛并见，舌淡紫", "treatment": "益气活血", "common_formula": "补阳还五汤"},
    {"name": "痰湿证", "category": "气血津液辨证", "key_symptoms": "形体肥胖，胸闷痰多，苔白腻", "treatment": "燥湿化痰", "common_formula": "二陈汤"},
    {"name": "湿热证", "category": "气血津液辨证", "key_symptoms": "身重困倦，口苦口黏，苔黄腻", "treatment": "清热利湿", "common_formula": "甘露消毒丹"},
    {"name": "湿热瘀阻证", "category": "气血津液辨证", "key_symptoms": "疼痛固定，口苦，舌暗红苔黄腻", "treatment": "清热祛湿，理气活血", "common_formula": ""},
    {"name": "水湿内停证", "category": "气血津液辨证", "key_symptoms": "肢体浮肿，小便不利", "treatment": "利水渗湿", "common_formula": "五苓散"},
    {"name": "阴虚证", "category": "气血津液辨证", "key_symptoms": "五心烦热，盗汗，舌红少苔", "treatment": "滋阴", "common_formula": "六味地黄丸"},
    {"name": "阳虚证", "category": "气血津液辨证", "key_symptoms": "畏寒肢冷，面色㿠白，舌淡胖", "treatment": "温阳", "common_formula": "理中丸"},

    # 六经
    {"name": "太阳伤寒证", "category": "六经辨证", "key_symptoms": "恶寒发热，无汗，头身疼痛，脉浮紧", "treatment": "辛温解表", "common_formula": "麻黄汤"},
    {"name": "太阳中风证", "category": "六经辨证", "key_symptoms": "发热恶风，汗出，脉浮缓", "treatment": "解肌祛风，调和营卫", "common_formula": "桂枝汤"},
    {"name": "少阳证", "category": "六经辨证", "key_symptoms": "往来寒热，胸胁苦满，口苦咽干", "treatment": "和解少阳", "common_formula": "小柴胡汤"},
    {"name": "阳明经证", "category": "六经辨证", "key_symptoms": "壮热，大汗，大渴，脉洪大", "treatment": "清热生津", "common_formula": "白虎汤"},
    {"name": "阳明腑证", "category": "六经辨证", "key_symptoms": "潮热谵语，腹满便秘，苔黄燥", "treatment": "峻下热结", "common_formula": "大承气汤"},
    {"name": "太阴证", "category": "六经辨证", "key_symptoms": "腹满时痛，食不下，自利", "treatment": "温中散寒", "common_formula": "理中丸"},
    {"name": "少阴寒化证", "category": "六经辨证", "key_symptoms": "畏寒蜷卧，四肢厥冷，下利清谷", "treatment": "回阳救逆", "common_formula": "四逆汤"},
    {"name": "少阴热化证", "category": "六经辨证", "key_symptoms": "心烦不得眠，口燥咽干", "treatment": "育阴清热", "common_formula": "黄连阿胶汤"},
    {"name": "厥阴证", "category": "六经辨证", "key_symptoms": "寒热错杂，消渴，气上撞心", "treatment": "寒热并调", "common_formula": "乌梅丸"},

    # 卫气营血 / 三焦
    {"name": "卫分证", "category": "卫气营血辨证", "key_symptoms": "发热微恶寒，头痛，脉浮数", "treatment": "辛凉解表", "common_formula": "银翘散"},
    {"name": "气分证", "category": "卫气营血辨证", "key_symptoms": "壮热不恶寒，汗多口渴", "treatment": "清热泻火", "common_formula": "白虎汤"},
    {"name": "营分证", "category": "卫气营血辨证", "key_symptoms": "身热夜甚，心烦不寐，舌绛", "treatment": "清营透热", "common_formula": "清营汤"},
    {"name": "血分证", "category": "卫气营血辨证", "key_symptoms": "身热，斑疹，出血，舌深绛", "treatment": "凉血散血", "common_formula": "犀角地黄汤"},
    {"name": "上焦湿热证", "category": "三焦辨证", "key_symptoms": "恶寒身热，头重如裹，胸闷", "treatment": "宣化上焦湿热", "common_formula": "三仁汤"},
    {"name": "中焦湿热证", "category": "三焦辨证", "key_symptoms": "脘痞腹胀，身重，便溏", "treatment": "清化中焦湿热", "common_formula": "连朴饮"},
    {"name": "下焦湿热证", "category": "三焦辨证", "key_symptoms": "小便短赤，淋浊，带下黄臭", "treatment": "清利下焦湿热", "common_formula": "八正散"},

    # 其他常见
    {"name": "肝郁脾虚证", "category": "脏腑辨证", "key_symptoms": "胁胀腹痛，便溏，情志不畅加重", "treatment": "疏肝健脾", "common_formula": "逍遥散"},
    {"name": "肝肾阴虚证", "category": "脏腑辨证", "key_symptoms": "头晕目眩，腰膝酸软，五心烦热", "treatment": "滋补肝肾", "common_formula": "六味地黄丸"},
    {"name": "脾肾阳虚证", "category": "脏腑辨证", "key_symptoms": "畏寒肢冷，久泻不止，水肿", "treatment": "温补脾肾", "common_formula": "附子理中丸"},
    {"name": "心脾两虚证", "category": "脏腑辨证", "key_symptoms": "心悸失眠，食少乏力，面色萎黄", "treatment": "补益心脾", "common_formula": "归脾汤"},
    {"name": "心肾不交证", "category": "脏腑辨证", "key_symptoms": "心烦失眠，腰膝酸软，遗精", "treatment": "交通心肾", "common_formula": "交泰丸"},
    {"name": "肺脾气虚证", "category": "脏腑辨证", "key_symptoms": "咳喘气短，食少便溏", "treatment": "补益肺脾", "common_formula": "六君子汤"},
    {"name": "肝郁化火证", "category": "脏腑辨证", "key_symptoms": "急躁易怒，胁痛口苦，失眠", "treatment": "清肝泻火", "common_formula": "丹栀逍遥散"},
    {"name": "风痰阻络证", "category": "脏腑辨证", "key_symptoms": "口眼㖞斜，肢体麻木，舌强", "treatment": "祛风化痰通络", "common_formula": "牵正散"},
    {"name": "瘀血阻络证", "category": "气血津液辨证", "key_symptoms": "疼痛固定拒按，舌紫暗", "treatment": "活血通络", "common_formula": "身痛逐瘀汤"},
]

# --------------------------------------------------------------------------
# 方剂
# --------------------------------------------------------------------------
FORMULAS: list[dict] = [
    {"name": "麻黄汤", "source": "《伤寒论》", "category": "解表剂", "functions": "发汗解表，宣肺平喘", "indications": "外感风寒表实证", "composition_text": "麻黄 桂枝 苦杏仁 甘草"},
    {"name": "桂枝汤", "source": "《伤寒论》", "category": "解表剂", "functions": "解肌发表，调和营卫", "indications": "外感风寒表虚证", "composition_text": "桂枝 白芍 生姜 大枣 甘草"},
    {"name": "银翘散", "source": "《温病条辨》", "category": "解表剂", "functions": "辛凉透表，清热解毒", "indications": "温病初起", "composition_text": "金银花 连翘 桔梗 薄荷 竹叶 甘草 荆芥 淡豆豉 牛蒡子"},
    {"name": "桑菊饮", "source": "《温病条辨》", "category": "解表剂", "functions": "疏风清热，宣肺止咳", "indications": "风温初起，表热轻证", "composition_text": "桑叶 菊花 苦杏仁 连翘 薄荷 桔梗 甘草 芦根"},
    {"name": "小柴胡汤", "source": "《伤寒论》", "category": "和解剂", "functions": "和解少阳", "indications": "伤寒少阳证", "composition_text": "柴胡 黄芩 半夏 人参 甘草 生姜 大枣"},
    {"name": "逍遥散", "source": "《太平惠民和剂局方》", "category": "和解剂", "functions": "疏肝解郁，养血健脾", "indications": "肝郁血虚脾弱证", "composition_text": "柴胡 当归 白芍 白术 茯苓 甘草 薄荷 生姜"},
    {"name": "丹栀逍遥散", "source": "《内科摘要》", "category": "和解剂", "functions": "疏肝解郁，清热调经", "indications": "肝郁化火证", "composition_text": "牡丹皮 栀子 柴胡 当归 白芍 白术 茯苓 甘草"},
    {"name": "柴胡疏肝散", "source": "《景岳全书》", "category": "理气剂", "functions": "疏肝解郁，行气止痛", "indications": "肝气郁滞证", "composition_text": "陈皮 柴胡 川芎 香附 枳壳 白芍 甘草"},
    {"name": "半夏泻心汤", "source": "《伤寒论》", "category": "和解剂", "functions": "寒热平调，消痞散结", "indications": "寒热错杂之痞证", "composition_text": "半夏 黄芩 黄连 干姜 人参 甘草 大枣"},
    {"name": "白虎汤", "source": "《伤寒论》", "category": "清热剂", "functions": "清热生津", "indications": "气分热盛证", "composition_text": "石膏 知母 甘草 粳米"},
    {"name": "清营汤", "source": "《温病条辨》", "category": "清热剂", "functions": "清营解毒，透热养阴", "indications": "热入营分证", "composition_text": "水牛角 生地黄 玄参 麦冬 金银花 连翘 黄连 竹叶 丹参"},
    {"name": "犀角地黄汤", "source": "《备急千金要方》", "category": "清热剂", "functions": "清热解毒，凉血散瘀", "indications": "热入血分证", "composition_text": "水牛角 生地黄 赤芍 牡丹皮"},
    {"name": "黄连解毒汤", "source": "《外台秘要》", "category": "清热剂", "functions": "泻火解毒", "indications": "三焦火毒热盛证", "composition_text": "黄连 黄芩 黄柏 栀子"},
    {"name": "龙胆泻肝汤", "source": "《医方集解》", "category": "清热剂", "functions": "清泻肝胆实火，清利下焦湿热", "indications": "肝胆实火上炎或湿热下注", "composition_text": "龙胆 黄芩 栀子 柴胡 生地黄 泽泻 木通 车前子 当归 甘草"},
    {"name": "清胃散", "source": "《脾胃论》", "category": "清热剂", "functions": "清胃凉血", "indications": "胃火牙痛", "composition_text": "黄连 升麻 牡丹皮 生地黄 当归"},
    {"name": "导赤散", "source": "《小儿药证直诀》", "category": "清热剂", "functions": "清心利水养阴", "indications": "心经火热证", "composition_text": "生地黄 木通 竹叶 甘草"},
    {"name": "理中丸", "source": "《伤寒论》", "category": "温里剂", "functions": "温中祛寒，补气健脾", "indications": "脾胃虚寒证", "composition_text": "人参 干姜 白术 甘草"},
    {"name": "四逆汤", "source": "《伤寒论》", "category": "温里剂", "functions": "回阳救逆", "indications": "心肾阳衰寒厥证", "composition_text": "附子 干姜 甘草"},
    {"name": "真武汤", "source": "《伤寒论》", "category": "祛湿剂", "functions": "温阳利水", "indications": "阳虚水泛证", "composition_text": "附子 白术 茯苓 白芍 生姜"},
    {"name": "四君子汤", "source": "《太平惠民和剂局方》", "category": "补益剂", "functions": "益气健脾", "indications": "脾胃气虚证", "composition_text": "人参 白术 茯苓 甘草"},
    {"name": "六君子汤", "source": "《医学正传》", "category": "补益剂", "functions": "益气健脾，燥湿化痰", "indications": "脾胃气虚兼痰湿证", "composition_text": "人参 白术 茯苓 甘草 陈皮 半夏"},
    {"name": "参苓白术散", "source": "《太平惠民和剂局方》", "category": "补益剂", "functions": "益气健脾，渗湿止泻", "indications": "脾虚湿盛证", "composition_text": "人参 白术 茯苓 甘草 山药 莲子 白扁豆 薏苡仁 砂仁 桔梗"},
    {"name": "补中益气汤", "source": "《内外伤辨惑论》", "category": "补益剂", "functions": "补中益气，升阳举陷", "indications": "脾虚气陷证", "composition_text": "黄芪 人参 白术 甘草 当归 陈皮 升麻 柴胡"},
    {"name": "四物汤", "source": "《仙授理伤续断秘方》", "category": "补益剂", "functions": "补血调血", "indications": "营血虚滞证", "composition_text": "熟地黄 当归 白芍 川芎"},
    {"name": "八珍汤", "source": "《正体类要》", "category": "补益剂", "functions": "益气补血", "indications": "气血两虚证", "composition_text": "人参 白术 茯苓 甘草 熟地黄 当归 白芍 川芎"},
    {"name": "归脾汤", "source": "《正体类要》", "category": "补益剂", "functions": "益气补血，健脾养心", "indications": "心脾气血两虚证", "composition_text": "人参 黄芪 白术 茯苓 甘草 当归 龙眼肉 酸枣仁 远志 木香 生姜 大枣"},
    {"name": "六味地黄丸", "source": "《小儿药证直诀》", "category": "补益剂", "functions": "滋补肝肾", "indications": "肝肾阴虚证", "composition_text": "熟地黄 山茱萸 山药 泽泻 牡丹皮 茯苓"},
    {"name": "金匮肾气丸", "source": "《金匮要略》", "category": "补益剂", "functions": "补肾助阳", "indications": "肾阳不足证", "composition_text": "熟地黄 山茱萸 山药 泽泻 牡丹皮 茯苓 桂枝 附子"},
    {"name": "一贯煎", "source": "《续名医类案》", "category": "补益剂", "functions": "滋阴疏肝", "indications": "肝肾阴虚，肝气郁滞证", "composition_text": "北沙参 麦冬 当归 生地黄 枸杞子 川楝子"},
    {"name": "百合固金汤", "source": "《慎斋遗书》", "category": "补益剂", "functions": "滋养肺肾，止咳化痰", "indications": "肺肾阴亏，虚火上炎证", "composition_text": "百合 熟地黄 生地黄 当归 白芍 甘草 桔梗 玄参 贝母 麦冬"},
    {"name": "二陈汤", "source": "《太平惠民和剂局方》", "category": "祛痰剂", "functions": "燥湿化痰，理气和中", "indications": "湿痰证", "composition_text": "半夏 陈皮 茯苓 甘草 生姜 乌梅"},
    {"name": "温胆汤", "source": "《三因极一病证方论》", "category": "祛痰剂", "functions": "理气化痰，和胃利胆", "indications": "胆郁痰扰证", "composition_text": "半夏 竹茹 枳实 陈皮 甘草 茯苓 生姜 大枣"},
    {"name": "半夏白术天麻汤", "source": "《医学心悟》", "category": "祛痰剂", "functions": "化痰息风，健脾祛湿", "indications": "风痰上扰证", "composition_text": "半夏 白术 天麻 茯苓 陈皮 甘草 生姜 大枣"},
    {"name": "保和丸", "source": "《丹溪心法》", "category": "消食剂", "functions": "消食和胃", "indications": "食滞胃脘证", "composition_text": "山楂 神曲 半夏 茯苓 陈皮 连翘 莱菔子"},
    {"name": "血府逐瘀汤", "source": "《医林改错》", "category": "理血剂", "functions": "活血化瘀，行气止痛", "indications": "胸中血瘀证", "composition_text": "桃仁 红花 当归 生地黄 川芎 赤芍 牛膝 桔梗 柴胡 枳壳 甘草"},
    {"name": "补阳还五汤", "source": "《医林改错》", "category": "理血剂", "functions": "补气活血通络", "indications": "气虚血瘀之中风", "composition_text": "黄芪 当归 赤芍 地龙 川芎 桃仁 红花"},
    {"name": "桃红四物汤", "source": "《医宗金鉴》", "category": "理血剂", "functions": "养血活血", "indications": "血虚兼血瘀证", "composition_text": "熟地黄 当归 白芍 川芎 桃仁 红花"},
    {"name": "天麻钩藤饮", "source": "《中医内科杂病证治新义》", "category": "治风剂", "functions": "平肝息风，清热活血，补益肝肾", "indications": "肝阳偏亢，肝风上扰证", "composition_text": "天麻 钩藤 石决明 栀子 黄芩 川牛膝 杜仲 桑寄生 益母草 夜交藤 茯神"},
    {"name": "牵正散", "source": "《杨氏家藏方》", "category": "治风剂", "functions": "祛风化痰，通络止痉", "indications": "风痰阻于头面经络之口眼㖞斜", "composition_text": "白附子 僵蚕 全蝎"},
    {"name": "五苓散", "source": "《伤寒论》", "category": "祛湿剂", "functions": "利水渗湿，温阳化气", "indications": "膀胱气化不利之蓄水证", "composition_text": "猪苓 泽泻 白术 茯苓 桂枝"},
    {"name": "八正散", "source": "《太平惠民和剂局方》", "category": "祛湿剂", "functions": "清热泻火，利水通淋", "indications": "湿热淋证", "composition_text": "车前子 瞿麦 萹蓄 滑石 栀子 甘草 木通 大黄"},
    {"name": "三仁汤", "source": "《温病条辨》", "category": "祛湿剂", "functions": "宣畅气机，清利湿热", "indications": "湿温初起及暑温夹湿", "composition_text": "苦杏仁 白豆蔻 薏苡仁 滑石 通草 竹叶 厚朴 半夏"},
    {"name": "连朴饮", "source": "《霍乱论》", "category": "祛湿剂", "functions": "清热化湿，理气和中", "indications": "湿热霍乱", "composition_text": "黄连 厚朴 石菖蒲 半夏 栀子 淡豆豉 芦根"},
    {"name": "酸枣仁汤", "source": "《金匮要略》", "category": "安神剂", "functions": "养血安神，清热除烦", "indications": "肝血不足，虚热内扰之虚烦不眠", "composition_text": "酸枣仁 甘草 知母 茯苓 川芎"},
    {"name": "天王补心丹", "source": "《校注妇人良方》", "category": "安神剂", "functions": "滋阴清热，养血安神", "indications": "阴虚血少，神志不安证", "composition_text": "生地黄 人参 玄参 丹参 茯苓 远志 桔梗 五味子 当归 天冬 麦冬 柏子仁 酸枣仁"},
    {"name": "大承气汤", "source": "《伤寒论》", "category": "泻下剂", "functions": "峻下热结", "indications": "阳明腑实证", "composition_text": "大黄 芒硝 厚朴 枳实"},
    {"name": "麻子仁丸", "source": "《伤寒论》", "category": "泻下剂", "functions": "润肠泄热，行气通便", "indications": "胃肠燥热之脾约证", "composition_text": "火麻仁 白芍 枳实 大黄 厚朴 苦杏仁"},
    {"name": "乌梅丸", "source": "《伤寒论》", "category": "驱虫剂", "functions": "温脏安蛔", "indications": "蛔厥证", "composition_text": "乌梅 细辛 干姜 黄连 当归 附子 蜀椒 桂枝 人参 黄柏"},
]

# --------------------------------------------------------------------------
# 通用术语
# --------------------------------------------------------------------------
TERMS: list[dict] = [
    # 舌质 term_type=1
    {"term_type": 1, "term": "淡红", "description": "正常舌质"},
    {"term_type": 1, "term": "淡白", "description": "主气血两虚、阳虚"},
    {"term_type": 1, "term": "红", "description": "主热证"},
    {"term_type": 1, "term": "舌尖红", "description": "主心火亢盛"},
    {"term_type": 1, "term": "舌边红", "description": "主肝胆火盛"},
    {"term_type": 1, "term": "绛", "description": "深红，主热入营血"},
    {"term_type": 1, "term": "紫", "description": "主血瘀或热盛"},
    {"term_type": 1, "term": "紫暗", "description": "主血瘀"},
    {"term_type": 1, "term": "暗红", "description": "主瘀热"},
    {"term_type": 1, "term": "淡暗", "description": "主气虚血瘀"},
    {"term_type": 1, "term": "青紫", "description": "主寒凝血瘀"},
    {"term_type": 1, "term": "胖大", "description": "主水湿痰饮"},
    {"term_type": 1, "term": "瘦小", "description": "主阴血不足"},
    {"term_type": 1, "term": "老", "description": "主实证"},
    {"term_type": 1, "term": "嫩", "description": "主虚证"},
    {"term_type": 1, "term": "齿痕", "description": "主脾虚湿盛"},
    {"term_type": 1, "term": "裂纹", "description": "主阴液亏虚"},
    {"term_type": 1, "term": "瘀点", "description": "主血瘀"},
    {"term_type": 1, "term": "瘀斑", "description": "主血瘀"},
    {"term_type": 1, "term": "舌下络脉迂曲", "description": "主血瘀"},
    {"term_type": 1, "term": "舌体强硬", "description": "主热入心包或中风"},
    {"term_type": 1, "term": "舌体颤动", "description": "主肝风内动"},
    {"term_type": 1, "term": "舌体歪斜", "description": "主中风"},
    {"term_type": 1, "term": "少津", "description": "主津液不足"},

    # 舌苔 term_type=2
    {"term_type": 2, "term": "薄白", "description": "正常苔或表证"},
    {"term_type": 2, "term": "薄黄", "description": "主风热或里热轻证"},
    {"term_type": 2, "term": "白苔", "description": "主寒证、湿证"},
    {"term_type": 2, "term": "黄苔", "description": "主热证"},
    {"term_type": 2, "term": "黄腻", "description": "主湿热"},
    {"term_type": 2, "term": "白腻", "description": "主寒湿或痰浊"},
    {"term_type": 2, "term": "厚腻", "description": "主痰湿积滞"},
    {"term_type": 2, "term": "薄", "description": "主病轻"},
    {"term_type": 2, "term": "厚", "description": "主病重或痰湿"},
    {"term_type": 2, "term": "少苔", "description": "主阴虚"},
    {"term_type": 2, "term": "无苔", "description": "主胃气大伤或阴虚"},
    {"term_type": 2, "term": "剥苔", "description": "主胃阴不足"},
    {"term_type": 2, "term": "花剥", "description": "主胃气阴两伤"},
    {"term_type": 2, "term": "燥", "description": "主津伤"},
    {"term_type": 2, "term": "糙", "description": "主津伤或食滞"},
    {"term_type": 2, "term": "滑", "description": "主水湿"},
    {"term_type": 2, "term": "润", "description": "正常或津液未伤"},
    {"term_type": 2, "term": "灰", "description": "主里热或寒湿"},
    {"term_type": 2, "term": "黑", "description": "主热极或寒盛"},
    {"term_type": 2, "term": "腐", "description": "主食积"},
    {"term_type": 2, "term": "稍黄", "description": "里热轻证"},
    {"term_type": 2, "term": "稍黄腻", "description": "湿热轻证"},

    # 脉象 term_type=3
    {"term_type": 3, "term": "浮", "description": "主表证"},
    {"term_type": 3, "term": "沉", "description": "主里证"},
    {"term_type": 3, "term": "迟", "description": "主寒证"},
    {"term_type": 3, "term": "数", "description": "主热证"},
    {"term_type": 3, "term": "滑", "description": "主痰湿、食积、妊娠"},
    {"term_type": 3, "term": "涩", "description": "主血瘀、精伤"},
    {"term_type": 3, "term": "弦", "description": "主肝胆病、痛证、痰饮"},
    {"term_type": 3, "term": "紧", "description": "主寒证、痛证"},
    {"term_type": 3, "term": "缓", "description": "主湿证或脾虚"},
    {"term_type": 3, "term": "虚", "description": "主虚证"},
    {"term_type": 3, "term": "实", "description": "主实证"},
    {"term_type": 3, "term": "洪", "description": "主气分热盛"},
    {"term_type": 3, "term": "细", "description": "主气血两虚、湿证"},
    {"term_type": 3, "term": "濡", "description": "主虚证、湿证"},
    {"term_type": 3, "term": "弱", "description": "主气血不足"},
    {"term_type": 3, "term": "微", "description": "主阳衰、气血大虚"},
    {"term_type": 3, "term": "结", "description": "主阴盛气结"},
    {"term_type": 3, "term": "代", "description": "主脏气衰微"},
    {"term_type": 3, "term": "促", "description": "主阳盛实热"},
    {"term_type": 3, "term": "长", "description": "主阳证"},
    {"term_type": 3, "term": "短", "description": "主气病"},
    {"term_type": 3, "term": "芤", "description": "主失血、伤阴"},
    {"term_type": 3, "term": "革", "description": "主亡血、失精"},
    {"term_type": 3, "term": "牢", "description": "主阴寒内实"},
    {"term_type": 3, "term": "伏", "description": "主邪闭、厥证"},
    {"term_type": 3, "term": "疾", "description": "主阳极阴竭"},
    {"term_type": 3, "term": "弦细", "description": "复合脉，肝郁血虚"},
    {"term_type": 3, "term": "弦滑", "description": "复合脉，肝郁痰湿"},
    {"term_type": 3, "term": "弦滑稍数", "description": "复合脉，肝郁湿热"},
    {"term_type": 3, "term": "沉细", "description": "复合脉，里虚"},
    {"term_type": 3, "term": "沉滑", "description": "复合脉，痰饮内停"},
    {"term_type": 3, "term": "细弱", "description": "复合脉，气血两虚"},
    {"term_type": 3, "term": "滑数", "description": "复合脉，痰热"},
    {"term_type": 3, "term": "濡缓", "description": "复合脉，湿困脾阳"},

    # 炮制 term_type=5
    {"term_type": 5, "term": "生用", "description": "未经炮制"},
    {"term_type": 5, "term": "清炒", "description": "不加辅料炒制"},
    {"term_type": 5, "term": "麸炒", "description": "麦麸为辅料炒制"},
    {"term_type": 5, "term": "土炒", "description": "灶心土为辅料炒制"},
    {"term_type": 5, "term": "炒焦", "description": "炒至外焦内黄"},
    {"term_type": 5, "term": "炒炭", "description": "炒至外部焦黑"},
    {"term_type": 5, "term": "酒炙", "description": "黄酒为辅料炙制"},
    {"term_type": 5, "term": "醋炙", "description": "米醋为辅料炙制"},
    {"term_type": 5, "term": "盐炙", "description": "食盐水为辅料炙制"},
    {"term_type": 5, "term": "蜜炙", "description": "炼蜜为辅料炙制"},
    {"term_type": 5, "term": "姜汁炙", "description": "生姜汁为辅料炙制"},
    {"term_type": 5, "term": "砂烫", "description": "河砂为辅料烫制"},
    {"term_type": 5, "term": "煅制", "description": "高温煅烧"},
    {"term_type": 5, "term": "蒸制", "description": "隔水或直接蒸制"},
    {"term_type": 5, "term": "酒蒸", "description": "黄酒拌蒸"},
    {"term_type": 5, "term": "炮制", "description": "通用炮制"},
    {"term_type": 5, "term": "矾制", "description": "白矾为辅料制"},
    {"term_type": 5, "term": "切片", "description": "切制成片"},

    # 煎服法 term_type=6
    {"term_type": 6, "term": "水煎服", "description": "常规煎服"},
    {"term_type": 6, "term": "先煎", "description": "矿物、贝壳类先煎"},
    {"term_type": 6, "term": "后下", "description": "芳香类后下"},
    {"term_type": 6, "term": "包煎", "description": "细小或带绒药物包煎"},
    {"term_type": 6, "term": "另煎", "description": "贵重药单独煎"},
    {"term_type": 6, "term": "烊化", "description": "胶类药溶化服"},
    {"term_type": 6, "term": "冲服", "description": "粉末或液体药冲服"},
    {"term_type": 6, "term": "温服", "description": "药液温时服"},
    {"term_type": 6, "term": "饭后服", "description": "饭后服用"},
    {"term_type": 6, "term": "饭前服", "description": "饭前服用"},
    {"term_type": 6, "term": "日一剂", "description": "每日一剂"},
    {"term_type": 6, "term": "分早晚温服", "description": "分两次温服"},
    {"term_type": 6, "term": "机械煎药", "description": "代煎服务"},
]
